### PR TITLE
Make the contact us usable :)

### PR DESCRIPTION
**Pull request by ooade**

### CODE REVIEW

**Comment by ooade** [comment]
@Developerayo Maybe try adding some prettier configs so my editor won't keep doing this 😓

**Comment by Developerayo** [comment]
Haha 😂😂
Will push that today.

**Comment by Developerayo** [comment]
Button not showing on mobile
Were the screenshot stops is were the section stops, button is unavailable. 
Screenshot_20190522-123904

**Comment by ooade** [comment]
@Developerayo it probably isn't showing on master, as well

**Comment by Developerayo** [comment]
Yh, it isn't, I'll check and see what this issue is. But if you find it first, push.

**Pull request merged**
