### PR TITLE
Update header to flex the screen width

### PR DESCRIPTION
**Pull request by Quadriphobs1**
Make the header to full the width screen and removed the comment `trick` used to make the side button place well

### CODE REVIEW

**Comment by Quadriphobs1** [comment]
Actually applied on all `html` pages

**Comment by Developerayo** [comment]
Ohh yes! my bad
I meant could you help removed the none breaking space `&nbsp;` from where it was inserted?

**Comment by Quadriphobs1** [comment]
Removed as well... Guess u missed that part . :eyes:

**Comment by Developerayo** [comment]
Oh shit, hahahaha

**Comment by Developerayo** [comment]
Just saw it.
Merging,

Thanks, Chief! 🚀

**Comment by Developerayo** [comment]
I forgot to test for mobile, the menu button is absent @Quadriphobs1

**Comment by Quadriphobs1** [comment]
Ohhh will look over to that... Forgot to test for mobile as well ... Insidious bug

**Pull request merged**
